### ISSUE TITLE
Implementation of a new extension providing `struct` and `Vector` types

### ISSUE THREAD

**Issue by paugier** [hpyproject/hpy#148] opened 2020-12-27 21:57 UTC
From my experience with writing numerical codes in pure Python style, we lack a container for homogeneous objects. I wrote a description (https://github.com/paugier/nbabel/blob/master/py/vector.md) of a possible API of an extension that would fix this issue.

It seems to me that it would be a great achievement for HPy to show that such project can be implemented with HPy with very good performance (first with PyPy). We could apply the extension to the N-Body problem (see https://github.com/paugier/nbabel) and show that numerical pure Python codes could be very efficient. It would be a great demonstration for HPy and moreover the extension could be useful in real life codes.

It seems to me that implementing a first limited version of the core of this extension in HPy would require much less work than porting enough Numpy to HPy. Good results with `Vector` would be an awesome argument for HPy so `Vector` could be a good first serious target for HPy. I would be very interested to get your point of view on these ideas.

**Comment by mattip** [comment] 2020-12-28 04:11
Isn’t the array module meant to supply a 1d homogeneous container?

**Comment by paugier** [comment] 2020-12-28 06:48
`array.array` can only contain few simple numerical types (https://docs.python.org/3/library/array.html). Moreover, 

```python
In [1]: from array import array                                                 
In [2]: a = array("f", [1., 1.])                                                
In [3]: 2*a                                                                     
Out[3]: array('f', [1.0, 1.0, 1.0, 1.0])
```
which is not what we usually want for such containers.

My proposition adds the possibility to declare types of fixed size `Vector4F = vp.Vector[float].subclass(size=4)` (that can be subclassed in Python) so that we can also declare types Vector of Vectors (for example `VecVec = Vector[Vector4F]`).

Of course, mathematical operators would apply elements-wise as for Numpy arrays.

Another aspects (not necessary for a first version): 

- being able to define in Python very simple classes that can be used in Vector (as explained in vector.md).
- being able to locally disable bound checks and type checks.

**Comment by mattip** [comment] 2020-12-28 08:20
I am afraid of the "yet another standard" way of doing this. You might want to take a look a the [Data API work](https://data-apis.github.io/array-api/latest/) going on to standardize the interfaces for these types of objects.

**Comment by paugier** [comment] 2020-12-28 08:41
I agree that it is "yet another standard" :slightly_smiling_face:

But it has not the same goal as Numpy and the Data API. This extension would be much smaller and simpler than any implementation of the Data API. It would be useful to implement things in pure Python. It would be complementary with libraries implementing the Data API.

Note that the core of the algorithm for the N-Body problem would be implemented with something like

```python
from math import sqrt
from hpyvec import Vector

class Point(Vector[float].subclass(size=3)):
    @property
    def x(self):
        return self[0]

    @property
    def y(self):
        return self[1]

    @property
    def z(self):
        return self[2]

    def norm(self):
        return sqrt(self.norm2())

    def norm_cube(self):
        norm2 = self.norm2()
        return norm2 * sqrt(norm2)

    def norm2(self):
        return self.x ** 2 + self.y ** 2 + self.z ** 2

Points = Vector[Point]

def compute_accelerations(accelerations, masses, positions):
    nb_particules = len(positions)
    for i0, position0 in enumerate(positions):
        for i1 in range(i0 + 1, nb_particules):
            delta = position0 - positions[i1]
            distance_cube = delta.norm_cube()
            accelerations[i0] -= masses[i1] / distance_cube * delta
            accelerations[i1] += masses[i0] / distance_cube * delta
```

**Comment by paugier** [comment] 2020-12-28 21:08
Things I like with this idea:

- Writing efficient numerical codes with Python implies nowadays avoiding too much interactions with the interpreter (CPython). Most tools/API for computations with Python are based on this limitation (Numpy, Cython, Numba, Pythran, Pandas, etc.). 

- Python is very nice for its object oriented syntax but because of the bad performance of its main interpreter, objects of classes defined in Python can't be used for computationally intensive parts.

- PyPy could be a great tool but writing everything in pure Python is (i) long and boring and (ii) not super efficient in particular because we lack a container like `Vector` (see the results of my [NBabel experiments](https://mail.python.org/pipermail/pypy-dev/2020-December/016087.html)). Moreover the existing extensions are (i) very inefficient and (ii) not adapted for OOP. Even with Numpy ported to HPy, Numpy (or the "Data API") wouldn't be sufficient to write very efficient codes in PyPy with OOP style (I don't think it would be possible to express what is expressed in the code above).

I guess Numpy arrays of objects are "just" arrays of references, so we would have the same limitations than today in PyPy with lists.

The proposed extension would nicely solve these problems. Finally, one would be able to use a Python extension and OOP for computational intensive tasks.

- The API and data layout is strongly inspired by Julia (so it's should be too bad). Knowing what can be done with this language, I tend to think it would be a good thing to be able to use such programming style also in Python.

Last, the core of this extension would be limited and relatively simple. We just provide an efficient container to build things with "low level" codes and not a huge library like Numpy or other implementations of the "Python array API standard".

To conclude, I think the "Python array API standard" (multidimensional arrays of numbers) and this proposition (efficient 1D vectors of Python objects) are 2 different complementary things.

**Comment by paugier** [comment] 2021-01-10 21:28
I thought again about this performance issue and this possible extension. One very important point is to be able to define immutable structures in Python and vectors of such structures. This is really a big advantage of Julia which makes it much more efficient (see https://github.com/paugier/nbabel/tree/master/py/microbench).

I completely rewrote a new version of the presentation of this potential new extension: https://github.com/paugier/nbabel/blob/master/py/vector_v2.md

It is much less focused on array programming and more on object-oriented programming. It would allow one to write the equivalents of very efficient Julia codes in Python, for example something like that:

```python
import ooperf as oo
@oo.native_bag
class Point4D:  # an immutable struct
    x: float
    y: float
    z: float
    w: float

    def square(self):
        return self.x**2 + self.y**2 + self.z**2 + self.w**2

Points = oo.Vector[Point4D]
points = Points.empty(1000)
```

**Comment by hodgestar** [comment] 2021-01-11 08:19
Hi Pierre,

The idea of adding strongly typed immutables to Python is interesting, but
I think outside the scope of HPy right now.

HPy *should* enable such types to be defined in C with less memory overhead
than in the existing C API -- specifically PyObject_HEAD can be removed in
some cases -- but its not clear that, e.g., the PyPy JIT will be able to
"see" that something is static when it could not before HPy.

If Python grew support for such immutable types, I'm sure the C API and HPy
would support it, but our goal is not to add new features to Python.

Perhaps if we succeed at our current goals we will add new goals later, but
our current goal of just making PyObjects properly opaque is already quite
ambitious. :)

- Simon

**Comment by paugier** [comment] 2021-01-11 09:35
Thanks a lot for your nice explanation. I thought it could have been possible to define immutable types with the CPython C API since there are plenty of immutable types in Python (for example `float` or `tuple`) and in Numpy (for example `np.int32`).

I may be completely wrong, but it seems to me that to port Numpy in HPy (#137), you need to be able to define `np.int32` (an immutable Python type) and arrays containing a native array of C `int`. I feel the decorator `oo.native_bag` and the abstract type `Vector` are mainly syntactic sugar around these features of a C API.

I'm going to have a look how `np.intc` is defined in Numpy :slightly_smiling_face:

**Comment by hodgestar** [comment] 2021-01-11 09:39
@paugier One can definitely make immutable types in C extensions! The issue is how the interpreter should *know* that a new type is immutable though.

**Comment by paugier** [comment] 2021-01-14 10:28
> The issue is how the interpreter should know that a new type is immutable though.

Thinking about it, it is actually surprising. I remember that I learned that knowing that an object is immutable was an interesting information for a compiler...

Another remark: I implemented the equivalent of `Point` and `Points` classes in Cython (https://github.com/paugier/nbabel/blob/master/py/microbench/util_cython.pyx). It's slightly faster than pure Python on CPython (still ~70 times slower than pure Python with PyPy!) but super super slow with PyPy.

Let's hope that with HPy, this situation will be improved!

**Comment by hodgestar** [comment] 2021-01-14 10:49
It is the plan / hope to write an HPy backend for Cython at some point.

**Comment by hodgestar** [comment] 2021-02-24 09:38
I'm going to close this issue as out of scope for HPy. It would be great to help support such efforts where it makes sense for HPy to do so, but we're also explicitly trying to avoid solving too many problems at once -- just introducing handles and contexts into the C API is a big enough task for right now!

**Closed by hodgestar** 2021-02-24 09:38 UTC
