### ISSUE TITLE
Enough mature for a HPy port of PicoNumpy? 

### ISSUE THREAD

**Issue by paugier** [hpyproject/hpy#17] opened 2020-02-29 14:38 UTC
I would like to port to HPy a tiny extension providing a (very very limited) Numpy-like array class: https://github.com/paugier/piconumpy

The project is explained in the README, which also contains a list of the functions of the CPython C-API used in PicoNumpy.

Do you think HPy will soon be mature enough for HPy ports of such tiny extensions?

**Comment by hodgestar** [comment] 2020-02-29 20:53
@paugier PicoNumpy looks like an excellent idea to try with HPy at this stage. A few of us are at an HPy sprint this week where we hope to implement support for creating custom Python types with HPy. Once that is in place, you should be able to mostly implement PicoNumpy on HPy. If you find any other blockers please let us know.

Once it's working we'd love to see the performance benchmarks you get!

**Comment by paugier** [comment] 2020-02-29 21:57
> an HPy sprint this week where we hope to implement support for creating custom Python types with HPy.

Exactly what I need for PicoNumpy! Have a fun and productive week then!

**Comment by hodgestar** [comment] 2020-03-06 19:30
@paugier We're working on adding types in https://github.com/pyhandle/hpy/pull/22.

**Comment by paugier** [comment] 2020-03-10 08:20
Just to say that I rewrote the C extension in PicoNumpy using `PyType_Slot`, `PyType_Spec` and `PyType_FromSpec` so that the extensions written with both APIs will be very similar.

I can test that as soon as #22 is ready.

The benchmark results will be interesting. Without HPy, it gives:

- With CPython

```raw
Julia                      :     1 * norm = 0.00534 s
Transonic-Pythran          : 0.564 * norm
Numpy                      :  18.2 * norm
PicoNumpy (purepy)         :  23.7 * norm
PicoNumpy (purepy_array)   :  21.7 * norm
PicoNumpy (Cython)         :  15.6 * norm
PicoNumpy (CPython C-API)  :   4.7 * norm
```

- With PyPy3

```raw
Julia                      :     1 * norm = 0.00534 s
Transonic-Pythran          : 0.603 * norm
Numpy                      :   183 * norm
PicoNumpy (purepy)         :   2.4 * norm
PicoNumpy (purepy_array)   :  3.73 * norm
PicoNumpy (Cython)         :   135 * norm
PicoNumpy (CPython C-API)  :  17.8 * norm
```

**Comment by antocuni** [comment] 2020-08-06 11:45
An update on this issue: I started to create an hpy version of piconumpy, incrementally porting the C/API version one function/method at a time.

You can follow the progress by looking at the hpy branch of our fork of piconumpy (I will open a PR when it's ready):
https://github.com/pyhandle/piconumpy/tree/hpy

**Comment by mattip** [comment] 2020-11-03 05:59
Could you try again with latest pypy 3.6 nightly? Also, it would be nice to add "how to run a benchmark" to the documentation

**Comment by mattip** [comment] 2020-11-03 06:28
Ahh, found "how to run" in https://github.com/pyhandle/piconumpy. I had to disable numpy and pythran, they miscompiled on PyPy my machine (somehow the correct headers did not get included and I got a missing `PyExc_ValueError`, it should have been `PyPyExc_ValueError`). 

I got these results:
```
matti@matti-ryzen:~/piconumpy/bench$ export PYTHON=~/pypy3.6-HEAD/bin/pypy
matti@matti-ryzen:~/piconumpy/bench$ make
~/pypy3.6-HEAD/bin/pypy make_bench_piconumpy.py
~/pypy3.6-HEAD/bin/pypy tmp.py
Julia                      :     1 * norm = 0.00197 s
PicoNumpy (purepy)         :  3.88 * norm
PicoNumpy (purepy_array)   :  5.77 * norm
PicoNumpy (Cython)         :   224 * norm
PicoNumpy (CPython C-API)  :  26.2 * norm
matti@matti-ryzen:~/piconumpy/bench$ unset PYTHON
matti@matti-ryzen:~/piconumpy/bench$ make
python tmp.py
Julia                      :     1 * norm = 0.00197 s
PicoNumpy (purepy)         :  32.2 * norm
PicoNumpy (purepy_array)   :  30.9 * norm
PicoNumpy (Cython)         :  28.2 * norm
PicoNumpy (CPython C-API)  :  7.84 * norm
```

This is on a AMD Ryzen 9 3900X 12-Core Processor and CPython=`Python 3.8.6 | packaged by conda-forge`,

**Comment by paugier** [comment] 2020-11-03 08:54
> Could you try again with latest pypy 3.6 nightly?

There is something that I don't understand. I though `hpy.devel` would be included in PyPy.

$ pypy --version                                                                                                                                                             
Python 3.6.12 (4caae5a29a71, Nov 03 2020, 02:00:15)
[PyPy 7.3.4-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

$ pypy -c "import hpy.devel"                                                                                                                                                 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hpy.devel'

**Comment by paugier** [comment] 2020-11-03 09:21
With CPython, I also get some warnings (which are turned into errors because of `-Werror`)

```
piconumpy/_piconumpy_hpy.c: In function ‘zeros_impl’:
piconumpy/_piconumpy_hpy.c:228:13: warning: ‘result’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  228 |       result->data[i] = 0;
      |       ~~~~~~^~~~~~
piconumpy/_piconumpy_hpy.c: In function ‘zeros_trampoline’:
piconumpy/_piconumpy_hpy.c:228:13: warning: ‘result’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  228 |       result->data[i] = 0;
      |       ~~~~~~^~~~~~
```

I can also obtain that with PyPy if I install hpy (with `pip install -e .`), but then pypy uses the hpy files for CPython and no hpy extension can be compiled. 
```
$ pypy -c "import hpy.devel as m; print(m)"                                                                                                                                  
<module 'hpy.devel' from '/home/pierre/Dev/hpy/hpy/devel/__init__.py'>
```

**Comment by antocuni** [comment] 2020-11-03 11:18
> I had to disable numpy and pythran, they miscompiled on PyPy my machine
@mattip : note that there is a script called `bench_cpy_vs_hpy.py` which does not need pythan, numpy, etc.

> There is something that I don't understand. I though hpy.devel would be included in PyPy.

no, the idea is that `hpy.devel` is the same for all python implementations, while `hpy.universal` is implementation-specific.
PyPy ships only its own version of `hpy.universal`.

The `hpy.universal` module in the hpy repo is for CPython only.
(although I realize now that `hpy.universal` is maybe not a very good name for something which is *not* universal 😅. The name comes from the fact that it's what you need to *load* universal extensions).

So, it is correct to install `hpy.devel` inside PyPy. However, I fear that right now it tries to compile `hpy.universal` as well (which it should not, since `hpy.universal` is already shipped by pypy); try to comment out the `ext_modules` inside hpy's `setup.py`.

**Comment by paugier** [comment] 2020-11-03 13:21
> The hpy.universal module in the hpy repo is for CPython only.

Ok I got it now!

I confirm that PyPy produces an extension `universal.pypy36-pp73-x86_64-linux-gnu.so`.

```bash
~/Dev/hpy master $ ls hpy/                                                                                                                                              
devel  tools  universal  universal.pypy36-pp73-x86_64-linux-gnu.so
~/Dev/hpy master $ pypy -c "import hpy.universal as m; print(m)"                                                                                                        
<module 'hpy.universal' from '/home/pierre/Dev/hpy/hpy/universal.pypy36-pp73-x86_64-linux-gnu.so'>
```

If i comment it in `hpy/setup.py`, I was able with PyPy to install `hpy.devel` and to produce `piconumpy._piconumpy_hpy.hpy.so`.

Then, this extension can be imported and used. For example, this works:

`pypy -c "from piconumpy.util_hpy import import_ext as i; ext = i(); arr = ext.zeros(4); print(arr.tolist())"`

Unfortunately, there is a problem with array multiplication and addition so some tests are failing and I can't run the benchmark. For example:

```
$ pypy -c "from piconumpy.util_hpy import import_ext as i; ext = i(); arr = ext.zeros(4); print(2+arr)"                    
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'array'
```

**Comment by antocuni** [comment] 2020-11-03 17:35
> I confirm that PyPy produces an extension universal.pypy36-pp73-x86_64-linux-gnu.so.

fixed by PR #114. Note that `universal.pypy36-pp73-x86_64-linux-gnu.so` is ignored by pypy anyway, because it imports `lib_pypy/hpy/universal.py` first.

> If i comment it in hpy/setup.py, I was able with PyPy to install hpy.devel

good! Note that you need a version of `hpy.devel` which matches the one of pypy's `hpy.universal`. For example, with the latest nightly:
```
$ /tmp/pypy-c-jit-100871-4caae5a29a71-linux64/bin/pypy3 
Python 3.6.12 (4caae5a29a71, Nov 03 2020, 02:00:15)
[PyPy 7.3.4-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
>>>> import hpy.universal
>>>> hpy.universal.get_version()
('0.1.dev723+gdba748d', 'dba748d')
```

> Unfortunately, there is a problem with array multiplication and addition so some tests are failing and I can't run the benchmark. 

Yes, I think this is because the pypy version does not fully support reversed slots. If you do `arr+2` instead of `2+arr` it works. PyPy should be fixed eventually, but in the meantime you can run `bench/bench_cpy_vs_hpy.py` which contains a tweaked version which runs on PyPy.

I tried to install piconumpy from scratch on a fresh pypy3, it seems to work well for me but you need to take care of installing the correct version of hpy.devel and to pass `--hpy-abi=universal` to setup.py. I paste here the full instructions in case someone needs them:

```
# download the latest pypy3 nightly
# ==================================

~/hpy $ /tmp/pypy-c-jit-100871-4caae5a29a71-linux64/bin/pypy3 -V
Python 3.6.12 (4caae5a29a71, Nov 03 2020, 02:00:15)
[PyPy 7.3.4-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

~/hpy $ /tmp/pypy-c-jit-100871-4caae5a29a71-linux64/bin/pypy3 -m ensurepip
[...]

# install hpy.devel dba748d on top of it
# ======================================

~/hpy $ git show --summary
commit dba748d
Merge: 51c0baa 4208706
Author: Antonio Cuni <anto.cuni@gmail.com>
Date:   Thu Oct 22 12:06:24 2020 +0200

    Merge pull request #108 from hpyproject/antocuni/more-sq-slots
    
    Enable and test all the remaning sq_* slots


~/hpy $ /tmp/pypy-c-jit-100871-4caae5a29a71-linux64/bin/pypy3 setup.py develop
[...]


# install piconumpy on pypy3
# ===========================

# NOTE the option --hpy=abi=universal!

$ cd ~/piconumpy
~/piconumpy $ /tmp/pypy-c-jit-100871-4caae5a29a71-linux64/bin/pypy3 setup.py --hpy-abi=universal build_ext -i

# run the benchmark
~/piconumpy $ PYTHONPATH=. /tmp/pypy-c-jit-100871-4caae5a29a71-linux64/bin/pypy3 bench/bench_cpy_vs_hpy.py 
CPython C-API:   0.66 seconds
HPy [Universal]: 0.34 seconds
```

**Comment by paugier** [comment] 2020-11-03 20:17
Just a feedback. 

1. I was able to run bench_cpy_vs_hpy.py with pypy!

2. Regarding the multiplication and addition: multiplication `arr * 2` works but not addition `arr + 2`:

```
$ pypy -c "from piconumpy.util_hpy import import_ext as i; ext = i(); arr = ext.zeros(2); arr[0] = 1; print((arr * 2).tolist())"        
[2.0, 0.0]
$ pypy -c "from piconumpy.util_hpy import import_ext as i; ext = i(); arr = ext.zeros(4); arr[0] = 1; print((arr + 2).tolist())"        
Segmentation fault (core dumped)
```

3. With CPython, there is the problem of the warning (turned into an error)
```
piconumpy/_piconumpy_hpy.c: In function ‘zeros_impl’:
piconumpy/_piconumpy_hpy.c:228:13: warning: ‘result’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  228 |       result->data[i] = 0;
      |       ~~~~~~^~~~~~
```
I don't know if it is due to a problem in _piconumpy_hpy.c or in hpy.

4.  With CPython and hpy master, I get:
```
CPython C-API:   1.77 seconds
Traceback (most recent call last):
  File "bench_cpy_vs_hpy.py", line 108, in <module>
    main()
  File "bench_cpy_vs_hpy.py", line 97, in main
    t = bench(pnp_hpy_universal, N_SLEDS, N_TIME)
  File "bench_cpy_vs_hpy.py", line 75, in bench
    solver(mod, board, x_init, y_init, u_init, v_init, 0.01, n_time)
  File "bench_cpy_vs_hpy.py", line 60, in solver
    values_one_step = mod.array([x0[k], y0[k], u0[k], v0[k]])
SystemError: function HPyArg_ParseKeywords cannot use the format character 'O'. Use 'O+' instead and close the the returned handle if the call returns successfully
```
Does it mean that _piconumpy_hpy.c should be modify?

**Comment by mattip** [comment] 2020-11-04 04:39
Does the documentation need updating in the [pyhandle/piconumpy/README.md](https://github.com/hpyproject/piconumpy#install-and-run-the-benchmarks) ?

**Comment by antocuni** [comment] 2020-11-04 09:12
> 1. I was able to run bench_cpy_vs_hpy.py with pypy!

🎉

> Regarding the multiplication and addition: multiplication arr * 2 works but not addition arr + 2:

this is "expected". If you look at the source code, it assumes we receive two arrays without doing any check. You get a segfault also on CPython without any HPy at all.

> 3. With CPython, there is the problem of the warning (turned into an error)

works for me with gcc 9.3.0 (from ubuntu 20.04). It's weird that you get a warning there, since `result` is clearly initialized inside `Array_empty`.

> 4. With CPython and hpy master, I get:
[...]
Does it mean that _piconumpy_hpy.c should be modify?

yes... as you probably guessed, the API is very fluid and subject to change right now :).
Although we are still discussing about the best way to handle arguments, so maybe it's a good idea to wait a bit before fixing piconumpy.

**Comment by antocuni** [comment] 2020-11-04 10:10
> Does the documentation need updating in the pyhandle/piconumpy/README.md ?

very likely, I never touched it

**Comment by paugier** [comment] 2020-11-04 22:18
> > Does the documentation need updating in the pyhandle/piconumpy/README.md ?

> very likely, I never touched it

Note that I can really work on this part. I can also adapt the main benchmark to avoid using Numpy (except for the bench using Numpy of course). Maybe it's reasonable to wait until the hpy branch is merged and it works a bit better. Anyway, it may be good not to communicate too much on this piconumpy thing until the performance of hpy extensions is a bit better. For now, on PyPy, the pure Python piconumpy is still much much faster than the hpy version. And PyPy hpy is still much slower than the standard C ext with Cpython.

It may be due to the type of benchmark, for which there are really a lot of C calls from Python (which explains why Julia and Pythran are so good). So it may be that this benchmark is too hard for Python with C extensions... I wonder whether PyPy JIT can do a good job in this situation even with hpy...

**Comment by rlamy** [comment] 2020-11-19 14:53
> And PyPy hpy is still much slower than the standard C ext with Cpython.

I wanted to double-check that, but I actually find that PyPy performance is on par with CPython!
Unless I've made a mistake (which is entirely possible, given the state of our infrastructure), here are my timings when running `bench_cpy_vs_hpy.py`:
* With pypy3-latest + `hpy.devel 0.1.dev723+gdba748d`:
```
CPython C-API:   8.51 seconds
HPy [Universal]: 2.81 seconds
```
* With CPython 3.6.11 + `hpy.devel 0.1.dev723+gdba748d`:
```
CPython C-API:   2.87 seconds
HPy [Universal]: 3.56 seconds
HPy [CPy ABI]:   2.96 seconds
```
Note: this isn't a careful benchmark, differences smaller than 0.2 s are unlikely to be significative.
Note2: the slowdown with the universal ABI on CPython has presumably been fixed by PR #117.

**Comment by antocuni** [comment] 2020-11-19 16:45
uh, this is interesting. I am using these versions:
* self-compiled pypy at rev e83290af3fa9
* `hpy.devel 0.1.dev756+g848192d`
* Python 3.7.3 (I think it's the one shipped by ubuntu)

```
(hpy) bencher7 piconumpy $ PYTHONPATH=. python bench/bench_cpy_vs_hpy.py 
CPython C-API:   1.55 seconds
HPy [Universal]: 2.07 seconds
HPy [CPy ABI]:   1.84 seconds
(hpy) bencher7 piconumpy $ PYTHONPATH=. ~/pypy/quickbranch/pypy/goal/pypy3-c bench/bench_cpy_vs_hpy.py 
CPython C-API:   5.53 seconds
HPy [Universal]: 2.70 seconds
```

here, pypy+hpy is ~70% slower than CPython. @rlamy: what is the precise version of pypy you are using?
It might be that the culprit is pypy itself, because it seems that my pypy+hpy is almost as fast as your, but on all the other benchmarks my machine is much faster.

Also, I have run these benchmark on bencher7: could you please re-run yours on bencher7 as well, to see whether it's dependent on the machine?

**Comment by rlamy** [comment] 2020-11-19 19:16
Trying again with:
* a pypy nightly from the hpy branch at 3c535adbdae2
* `hpy.devel==0.1.dev756+g848192d`
* CPython 3.7.8

I get for CPython:
```
CPython C-API:   2.98 seconds
HPy [Universal]: 4.15 seconds
HPy [CPy ABI]:   3.51 seconds
```
and for PyPy:
```
CPython C-API:   8.52 seconds
HPy [Universal]: 3.49 seconds
```

**Comment by paugier** [comment] 2020-12-08 09:52
With HPy git revision 7c832a2f and https://github.com/hpyproject/piconumpy/pull/1, I was able to run the full benchmarks with CPython 3.8.2 and PyPy3.7!

```
pypy --version                                                                                                                  
Python 3.7.9 (2f41560b7f20, Dec 07 2020, 02:00:17)
[PyPy 7.3.4-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

First the simpler benchmarks (bench_cpy_vs_hpy.py)

- CPython

```
CPython C-API:   1.83 seconds
HPy [CPy ABI]:   2.20 seconds
HPy [Universal]: 2.73 seconds
```

- PyPy3

```
CPython C-API:   5.88 seconds
HPy [Universal]: 3.17 seconds
```

Then, the full bench:

- CPython

```
Julia                      :     1 * norm = 0.00194 s
PicoNumpy (CPython C-API)  :  9.03 * norm
PicoNumpy (hpy CPy ABI)    :  9.87 * norm
PicoNumpy (hpy universal)  :  12.5 * norm
Transonic-Pythran          : 0.546 * norm
Numpy                      :  37.5 * norm
PicoNumpy (purepy)         :  39.2 * norm
PicoNumpy (purepy_array)   :  37.1 * norm
PicoNumpy (Cython)         :  28.5 * norm
```

- PyPy3

```
Julia                      :     1 * norm = 0.00194 s
PicoNumpy (CPython C-API)  :  33.3 * norm
PicoNumpy (hpy universal)  :    15 * norm
Transonic-Pythran          : 0.629 * norm
Numpy                      :   332 * norm
PicoNumpy (purepy)         :  4.36 * norm
PicoNumpy (purepy_array)   :  7.69 * norm
PicoNumpy (Cython)         :   247 * norm
```

**Comment by paugier** [comment] 2020-12-08 14:38
> Does the documentation need updating in the pyhandle/piconumpy/README.md ?

I added a session to explain what I do: https://github.com/paugier/piconumpy/tree/hpy-bench0#more-precise-notes-on-how-to-install-and-run-the-benchmarks-with-pypy

Things that would need to be improved: with my setup,

- with CPython, PicoNumpy (HPy CPy ABI) is still a bit (10%) slower than PicoNumpy (CPython C-API)
- HPy Universal is slower with PyPy than with CPython
- HPy Universal PyPy is still slower than PicoNumpy (CPython C-API) with CPython

**Comment by hodgestar** [comment] 2020-12-08 16:06
@paugier Thanks for this and it's great that we've reached the point where the benchmarks are all running!

Agreed with your conclusions. Our small microbenchmarks show much closer numbers for CPython C-API, CPython HPy and PyPy HPy (universal), so hopefully there are some small silly things that can be fixed to get the same good results here.

**Comment by hodgestar** [comment] 2021-02-24 09:30
@paugier Given that piconumpy benchmarks now run on HPy, perhaps we should close this issue and start a new one for investigating the performance regressions?

**Comment by hodgestar** [comment] 2021-03-04 08:36
@paugier Closing this issue, but please open new ones if you find gaps or things which could be improved.

**Closed by hodgestar** 2021-03-04 08:36 UTC
