### ISSUE TITLE
Re-enable cppcheck

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#188] opened 2021-03-26 15:05 UTC
In commit a91f8f9 (PR #187 ) I had to disable cppcheck, because it failed for no good reason.

I have no idea of what's happening, we should try again in some days/weeks and maybe re-enable it.

**Comment by thedrow** [comment] 2021-07-06 15:15
On CPPCheck 2.5 `make cppcheck` passes successfully.

This sounds like a weird bug that should be reported.

**Comment by antocuni** [comment] 2021-07-08 21:53
do you feel like making a PR with `cppcheck` 2.5 and see if it passes the CI?

**Comment by thedrow** [comment] 2021-07-11 12:53
Since snap didn't properly work, we'd probably need to install it using Linuxbrew, I guess.
If that's OK with you, I can do it.

**Comment by antocuni** [comment] 2021-09-12 15:00
Sorry for the late response. I don't know what is linuxbrew but as long as it works, that's ok with me :)

**Comment by thedrow** [comment] 2021-09-13 11:39
Homebrew for linux...

**Comment by fangerer** [comment] 2021-11-22 13:39
I've re-enabled `cppcheck` but using Ubuntu's version `1.90`. I think this is better than nothing for now. We may think about moving to a newer version.

**Comment by mattip** [comment] 2023-03-02 20:09
cppcheck is failing CI, and I think it is not a good investment of the core team to fix it. Perhaps someone will step up at some point but I think we should disable it.

**Comment by fangerer** [comment] 2023-03-02 20:11
@mattip I can already reproduce the problem in a virtual machine using nearly the same system and versions as GitHub's docker images. Maybe I can quickly find the problem but as you said, I won't invest too much time.

**Closed** 2023-03-04 16:20 UTC
